apiVersion: v1
kind: Service
metadata:
  name: testbin
  # namespace: bmi
  labels:
    app: testbin
spec:
  ports:
  - port: 8080
    targetPort: 8882
    name: http-testbin
  # externalIPs: [192.168.43.70]
  selector:
    app: testbin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testbin
  # namespace: bmi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testbin
        version: v1
    spec:
      containers:
      - name: testbin
        image: juzhen/testbin:v1
        imagePullPolicy: IfNotPresent
        # ports:
        # - containerPort: 8882
---

